service: products

frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 10
  logRetentionInDays: 1
  endpointType: regional
  environment:
    SERVICE_NAME: ${self:service}
    SUPPLIER_API_HOSTNAME: 'api.apotiguar.com.br'
    SUPPLIER_API_PORT: '64462'
    SUPPLIER_API_APPID: 'e03ad982449af87ade1899ffbc259eee'
    SUPPLIER_API_TOKEN: '47320fd4d355f668a37a5895c15f509720a33a355a8fcac0f18c6f68da243b27'
    SUPPLIER_API_METHOD: 'bnp_mdlog_get_list'

plugins:
  - serverless-python-requirements 
  - serverless-sentry

custom:
  sentry:
    dsn: https://b41a6186e7f64c1cb9c66079b90a9fde:93320261e04547f4a8001d178e349b6d@sentry.io/1188215 # URL provided by Sentry
  pythonRequirements:
    dockerizePip: non-linux    

functions:
  get:
    handler: get.handler
    description: Collects from supplier all information about given product id.
    events:
      - http:
          path: products/{id}
          method: get
          cors: true
